version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: Update and clean
          command: |
            apt-get update
            apt-get clean
      - run:
          name: Install make, gcc and valgrind
          command: |
            apt-get install -y make gcc valgrind
            apt-get update
            apt-get clean
      - checkout
      - run:
          name: Build and test measurement_client
          command: |
            set -e
            cd $HOME/project/src/measurement_client/src
            make
            valgrind --tool=memcheck ./run
            valgrind --tool=memcheck ./test
            ./test
            make clean
      - run:
          name: Build and test measurement_server
          command: |
            set -e
            cd $HOME/project/src/measurement_server/src
            make
            valgrind --tool=memcheck ./run
            valgrind --tool=memcheck ./test
            ./test
            make clean

