version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: Update and clean
          command: |
            apt-get update
            apt-get clean
      - checkout
      - run:
          name: Build measurement_client
          command: |
            ls
            echo $HOME
            ls $HOME
            ls $HOME/src
            cd src/measurement_client/src && make'
            cd src/measurement_client/src && make clean'



