version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: Update and install tools
          command: |
            apt-get install -y make gcc
            apt-get update
            apt-get clean
      - checkout
      - run:
          name: Build measurement_client
          command: |
            cd $HOME/embedded_client/src/measurement_client/src && make'
            cd $HOME/embedded_client/src/measurement_client/src && make'



