version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: Install Curl
          command: |
            set -x
            apt-get update
            apt-get install -y curl git
      - setup_remote_docker:
          reusable: true
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.05.0-ce.tgz
            tar --strip-components=1 -xvzf docker-17.05.0-ce.tgz -C /usr/local/bin
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Build embedded_service image to make sure it builds
          command: |
            set -x
            # At least check that it builds.
            export USER_UID=1000
            export USER=testuser
            docker-compose build
      - run:
          name: Start Containers
          command: |
            set -x
            export USER_UID=1000
            export USER=testuser
            docker-compose up -d
      - run:
          name: Build measurement_client
          command: |
            docker exec -it embedded_service bash -c 'cd $HOME/src/measurement_client/src && make'
            docker exec -it embedded_service bash -c 'cd $HOME/src/measurement_client/src && make clean'




